# Generated by Django 6.0.1 on 2026-01-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
